### ISSUE TITLE
setup with synology and fritzbox router - wrong tftp address

### ISSUE THREAD

**Issue by tobidemski** [samdbmg/dhcp-netboot.xyz#3]
Hey,

i found your project because you set up the netboot.xyz with an integrated proxy dhcp server.
I tried to use your image but if i try to network boot the tftp address is always the ip of my gateway.
It is possible to tell them to use the ip of the tftp server instead of gateway? Im not able to set the tftp server in my router (fritzbox) and due to my isp provider im currently not able to change this shitty configuration.
I also run this configuration on a synology through portainer.

I combined your setup with this one: https://www.technorabilia.com/dockerized-netboot-xyz-on-synology-nas-and-router/ (exluded the router configuration part in the post)
Im trying to avoid enabling the dhcp on the synology because its already running on my fritzbox which is running 24/7 and dont want do run two of them.

Im not sure but i think i need to edit the dnsmasq.conf to get this working. Like adding the tftp ip (in my case 192.168.1.6) at the end of each line of "dhcp-boot=..."

You copied the config from the dd-wrt part. But there is also mentioned to replace the ip with the one you define.
(https://github.com/linuxserver/docker-netbootxyz#dd-wrt) (see YOURSERVERIP)

```
DD-WRT
Administration -> Services -> Additional DNSMasq Options Set the following lines:

dhcp-match=set:bios,60,PXEClient:Arch:00000
dhcp-boot=tag:bios,netboot.xyz.kpxe,,YOURSERVERIP
dhcp-match=set:efi32,60,PXEClient:Arch:00002
dhcp-boot=tag:efi32,netboot.xyz.efi,,YOURSERVERIP
dhcp-match=set:efi32-1,60,PXEClient:Arch:00006
dhcp-boot=tag:efi32-1,netboot.xyz.efi,,YOURSERVERIP
dhcp-match=set:efi64,60,PXEClient:Arch:00007
dhcp-boot=tag:efi64,netboot.xyz.efi,,YOURSERVERIP
dhcp-match=set:efi64-1,60,PXEClient:Arch:00008
dhcp-boot=tag:efi64-1,netboot.xyz.efi,,YOURSERVERIP
dhcp-match=set:efi64-2,60,PXEClient:Arch:00009
dhcp-boot=tag:efi64-2,netboot.xyz.efi,,YOURSERVERIP
```

Maybe you can take a look and have some hint to help me out.

Image of the VM
![image](https://user-images.githubusercontent.com/17470007/137413821-ed843298-81fd-4bae-9e64-071400c8d8b9.png)

My docker-compose file:

```
---
version: "2.1"
services:
  netbootxyz:
    container_name: netbootxyz
    image: samdbmg/dhcp-netboot.xyz
    environment:
      - PUID=1026
      - PGID=100
      # samdbmg configuration
      - DHCP_RANGE_START=192.168.1.20
    volumes:
      - /volume1/docker/netboot.xyz/config:/config
      - /volume1/docker/netboot.xyz/assets:/assets #optional
    networks:
      netbootxyz_network:
        ipv4_address: 192.168.1.6
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
networks:
  netbootxyz_network:
    driver: macvlan
    driver_opts:
      parent: ovs_eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.250/32
```

EDIT:
Okay im not alone and the main problem is netboot.xyz.
See this issue: https://github.com/netbootxyz/netboot.xyz/issues/952
